### ISSUE TITLE
[Figma] We need figma design to start the front end development.

### ISSUE THREAD

**Issue by shubhansu-kr** [mvp-2003/Quikz#12]
### Description:
We need Figma design files to begin the frontend development of our quiz application. These designs will help define the UI/UX for the core features, ensuring a consistent and smooth user experience across the app.

### Requirements:
The Figma designs should cover the following pages and components:

1. **Home/Welcome Page**: 
   - Introduction to the quiz app.
   - Option to join or create a quiz.
   
2. **Quiz Creation Page**:
   - Form to create a new quiz (input fields for quiz name, question types, etc.).
   - Interface for adding multiple questions (MCQs, true/false, etc.).
   
3. **Quiz Participation Page**:
   - Interface for participants to join a quiz using a code.
   - Real-time display of questions and options to submit answers.
   
4. **Quiz Host Dashboard**:
   - Real-time display of participant responses.
   - Controls for navigating between questions.
   
5. **Results Page**:
   - Display the results or leaderboard after the quiz ends.
   - Breakdown of participant scores.

### Key Design Considerations:
- **Responsive design**: The application should be mobile-first but also optimized for larger screens.
- **Interactive elements**: Designs should focus on ease of use and real-time feedback (e.g., live updates for participants).
- **Modern, intuitive UI**: The design should reflect a clean, modern look that is easy to navigate.
  
### References:
For inspiration, please refer to applications like **Mentimeter** or similar quiz platforms that focus on live engagement with real-time feedback.

### Acceptance Criteria:
- Figma design files covering all the listed components and screens.
- The design aligns with the core functionality and features outlined.
- The design is shared with the team to initiate frontend development.

### Notes:
- This issue is a blocker for the frontend development phase.
- Please ensure all necessary assets (icons, images) are included in the design.

**Comment by shubhansu-kr** [comment]
@mvp-2003 , Can you get us some Mocks for the application ?

**Comment by mvp-2003** [comment]
I'm not sure how to do that. Can you give me a general idea? And I will try to prepare everything you need. Is that ok?

**Comment by shubhansu-kr** [comment]
I meant we need figma designs to determine how our frontend will look like. In React we will start creating what we will see in the figma design. Figma design is like an image which represents the expected UI of the application but it has more details like color code, pixel size etc...

**Comment by shubhansu-kr** [comment]
Here is an example : https://www.figma.com/community/file/1222060007934600841/responsive-landing-page-design-website-home-page-design-agency-website-ui-design. 

This kind of design for our website

**Comment by mvp-2003** [comment]
Alright. I will manage it.

**Comment by Prathamesh0901** [comment]
i would love to contribute to the frontend and backend of this project. Please let me know if there is any work i can do.

**Comment by shubhansu-kr** [comment]
For frontend we are waiting for figma designs. If you want to contribute there you can get the design for the website and share the link here. 

For backend i will be creating few issues for implementation of routes you can pick from there. Let me know which one you are interested in. 

Would you like to work on figma ?

**Comment by Prathamesh0901** [comment]
I would love to work on backend then. I don't have any experience in figma.

**Comment by Prathamesh0901** [comment]
I would love to work on backend then.

**Comment by shubhansu-kr** [comment]
Good to hear, will be creating multiple issues today for implementation of routes. You can pick up issues then.

**Comment by mvp-2003** [comment]
@shubhansu-kr I have brought in a friend who happens to be a UI/UX designer.

**Comment by shubhansu-kr** [comment]
Thanks @mvp-2003

**Comment by parth-1372** [comment]
Hi @shubhansu-kr , @mvp-2003 I Know Frontend But Do not know much about Figman Design . So currently Any scope for Frontend or Backend Contribution?

**Comment by shubhansu-kr** [comment]
@parth-1372 We can proceed with the frontend work only when we know how UI should be. I have created few backend tasks. You can have a look at them. 

If you really want to contribute to frontend, that would be a great help since we don't have much of frontend contributor. See if you can find any relevant quiz application UI on the internet and we will finalise that. You can start working there then.

**Comment by shubhansu-kr** [comment]
@Prathamesh0901 Issues created for backend. You can have a look.

**Comment by PrathameshGujar08** [comment]
Hello,
A Working Frontend Developer here(React, Angular, Typescript). I would like to contribute the frontend for this. Please let me know when you have some work related to me. Till then I would try on other issues. Thanks

**Comment by motuncoded** [comment]
Hello, I am a frontend developer. 
Stack: Javascript, Typescript

**Comment by PrathameshGujar08** [comment]
> Hello, A Working Frontend Developer here(React, Angular, Typescript). I would like to contribute the frontend for this. Please let me know when you have some work related to me. Till then I would try on other issues. Thanks

Heyy @mvp-2003  You assigned me this issue but I cant make a Figma Design what I meant was once we have the design I am willing to work on it

**Comment by shubhansu-kr** [comment]
> Hello, I am a frontend developer. Stack: Javascript, Typescript I would like to work on the frontend.

Hi @motuncoded , Thanks for showing interest. I am assigning you this issue. Please share you figma proposal for this. Once approved we can get started on the coding part.

**Comment by motuncoded** [comment]
I can only interpret the design from figma... Hopefully we get a design soon

**Comment by shubhansu-kr** [comment]
Same @motuncoded . Haha, will get design soon

**Comment by asmb123** [comment]
@shubhansu-kr I would like to work on this, I will start designing the UI in figma.

**Comment by shubhansu-kr** [comment]
@asmb123 Please start, I will assign you this issue when i get access to my laptop

**Comment by asmb123** [comment]
> @asmb123 Please start, I will assign you this issue when i get access to my laptop

https://www.figma.com/design/s0eI8YDamF3Gqh3Bt5et99/asmbDevFigma?node-id=116-4&t=aVQjW25eXRfw55ia-1
please point out any changes you need in the ui, i'll start coding the ui once you approve.

**Comment by motuncoded** [comment]
Can we assigned for frontend part?

**Comment by shubhansu-kr** [comment]
@asmb123 , Thank you for the contributing. 

Design looks good, however we can imporve few things, 
1. Let's get user login/signup design. 
2. For quiz questions lets create a more visible design. Options in one column will make it more readable. 
3. Lets try to make quiz create cards a little subtle. It's too bold.
4. We can move with this color scheme but would have loved to see a light mode as well.
5. Please see if you can take inspiration from any existing website which has a more subtle design.

**Comment by shubhansu-kr** [comment]
> Can we assigned for frontend part?

Let's get figma design sorted first. Thanks

**Comment by motuncoded** [comment]
Ok Nice

**Comment by asmb123** [comment]
@shubhansu-kr check this https://www.figma.com/design/s0eI8YDamF3Gqh3Bt5et99/asmbDevFigma?node-id=116-4&t=DAqaVMxx8ZmBeHsk-1
light mode added, quiz page changed, was thinking of using clerk or any other auth service.

**Comment by shubhansu-kr** [comment]
> @shubhansu-kr check this https://www.figma.com/design/s0eI8YDamF3Gqh3Bt5et99/asmbDevFigma?node-id=116-4&t=DAqaVMxx8ZmBeHsk-1 light mode added, quiz page changed, was thinking of using clerk or any other auth service.

There was one more design contribution i just mentioned above. Can you two work together to finalise design. 

This updated design is an improvement. It looks better. Can you please add reference to clerk as an auth service which you mentioned.

Thanks

**Comment by asmb123** [comment]
> > @shubhansu-kr check this https://www.figma.com/design/s0eI8YDamF3Gqh3Bt5et99/asmbDevFigma?node-id=116-4&t=DAqaVMxx8ZmBeHsk-1 light mode added, quiz page changed, was thinking of using clerk or any other auth service.
> 
> There was one more design contribution i just mentioned above. Can you two work together to finalise design.
> 
> This updated design is an improvement. It looks better. Can you please add reference to clerk as an auth service which you mentioned.
> 
> Thanks

Here is the clerk quickstart guide : https://clerk.com/docs/quickstarts/react
Cleark provides already built nice looking UI like : https://clerk.com/docs/components/authentication/sign-up

I will redesign the website UI as similar as the mobile version design you mentioned above.

**Comment by shubhansu-kr** [comment]
Thank you @asmb123 , for your valuable contribution

**Comment by asmb123** [comment]
> Thank you @asmb123 , for your valuable contribution

https://www.figma.com/design/s0eI8YDamF3Gqh3Bt5et99/asmbDev?node-id=116-4&t=fWjmw2JtaVnonXTQ-1
you may check this, i have changed it a little, further design improvements, animations, extra svgs for good looking UI and extra features can be done along the way.

**Comment by asmb123** [comment]
@

> > Thank you @asmb123 , for your valuable contribution
> 
> https://www.figma.com/design/s0eI8YDamF3Gqh3Bt5et99/asmbDev?node-id=116-4&t=fWjmw2JtaVnonXTQ-1 you may check this, i have changed it a little, further design improvements, animations, extra svgs for good looking UI and extra features can be done along the way.

@shubhansu-kr If you approve shall I start by making a pull request of the Landing page in this issue and raising other pages issues or you will do that?

**Comment by shubhansu-kr** [comment]
Hi @asmb123 , add the link in documentation file and create the PR. Create new issues for other pages if you need.

**Comment by asmb123** [comment]
> Hi @asmb123 , add the link in documentation file and create the PR. Create new issues for other pages if you need.

Made the PR!
once accepted I will make the landing page and raise issue for other pages. Thank you.

**Comment by shubhansu-kr** [comment]
Merged @asmb123
