### ISSUE TITLE
[Server] Quiz Use Case implementation.

### ISSUE THREAD

**Issue by shubhansu-kr** [mvp-2003/Quikz#21]
###  Implement Quiz Routes (Create, Update, Delete)

**Summary:**
This pull request introduces the implementation of quiz-related API routes, including the ability to create, update, and delete quizzes. The assignee should use the existing **User Authentication** route as a guide to maintain consistency and follow best practices in route structure and controller logic.

**Key Actions for Assignee:**
1. **Comment on Issue:**
   - Before starting the implementation, comment on the issue with the proposed `Quiz` model structure and the exact routes you plan to implement.
   - The `Quiz` model should be designed to capture essential quiz data like `title`, `questions`, `answers`, and timestamps.

2. **Route Implementation:**
   - Implement the following quiz-related routes:
     - **Create a quiz:** `POST /api/quiz`
     - **Update a quiz:** `PUT /api/quiz/:id`
     - **Delete a quiz:** `DELETE /api/quiz/:id`
   - Follow the patterns used in the `User Authentication` route for controller structure, validation, and error handling.

3. **Refer to Documentation:**
   - The routes can be found in `documentation.md` for detailed specifications and expected behavior.

**Future Guidance:**
- The implementation of these quiz routes will serve as the foundation for further quiz-related features like fetching quizzes or taking a quiz.
- Ensure to add validation logic for incoming data (quiz title, questions, etc.) and handle errors appropriately.

**Testing:**
- Test the functionality of each quiz route via unit tests or manual testing (e.g., using Postman) to ensure correctness and proper error handling.

**Comment by Prathamesh0901** [comment]
Quiz Schema:
    {
        "title": "string",
        "questions": [
            {
                "question": "string",
                "options": {
                    "1": "option1",
                    "2": "option2",
                    ...
                },
                "ansewerOption": "integer"
            }
        ],
        "createdAt": "time",
        "updatedAt": "time"
    }

Routes:
    1. POST /api/quiz
        create quiz route. will be authorized route(middleware will be added after implementing authentication)

    2. UPDATE /api/quiz/:id 
        update quiz title, questions and correct option(will be authorized too)

    3. DELETE /api/quiz/:id
        delete quiz(authorized)

@shubhansu-kr need any changes?

**Comment by shubhansu-kr** [comment]
We would need to Create Quiz right ?.

**Comment by Prathamesh0901** [comment]
yes we do. there is a post route on /api/quiz where a new quiz will be created

**Comment by shubhansu-kr** [comment]
@Prathamesh0901, Looks fine. You can start contributing

**Comment by shubhansu-kr** [comment]
Issue resolved. Closing
