### ISSUE TITLE
[Server] Implement Quiz Templates and PreBuit Quizzes API routes

### ISSUE THREAD

**Issue by shubhansu-kr** [mvp-2003/Quikz#25]
## Quiz Templates & Prebuilt Quizzes
**Description:**  
Implement templates for quizzes, allowing users to reuse predefined quiz structures.

**Tasks:**
- Create a template model.
- Implement routes to create, manage, and clone quiz templates.
- Enable users to create quizzes from templates.

**Dependencies:**  
- **Quiz Management** (Issue 2) and **Question Bank** (Issue 5) to pull quiz structures and questions.

**Guidelines for Assignee:**
- Comment on the issue with the approach for creating quiz templates.

**Comment by Prototype4988** [comment]
Hi @shubhansu-kr I would like to look into this issue. can you assign it to me.

**Comment by shubhansu-kr** [comment]
Hi @Prototype4988 , Assigned you this task. Please go through the guidelines and discuss the approach before contributing.

**Comment by shubhansu-kr** [comment]
@Prototype4988 Any update ?

**Comment by Prototype4988** [comment]
Im currently occupied. Ill unassign myself.

**Comment by Trishank-K** [comment]
Hey! Please assign me this issue

**Comment by shubhansu-kr** [comment]
@Trishank-K , Assigning you this issue. 

Please do me a favour, I have merged a lot of API implementation but haven't personally tested them. If you get chance, please verify the API and documentation mapping and then start the implementation for the same. 

You can create seperate PRs if you find any abnormality, 

Thank you

**Comment by Trishank-K** [comment]
Ok sirrr! On it

**Comment by shubhansu-kr** [comment]
Thanks @Trishank-K

**Comment by Trishank-K** [comment]
Hey @shubhansu-kr 
can you please give me a brief idea of what is templates and what is expected of it?
Maybe some schema that you can provide or some idea of what you mean by quiz structures?

**Comment by shubhansu-kr** [comment]
Templates are basically set of questions which any user can choose to get started with quiz while creating one. Think of it as you are creating a quiz but dont want to enter manually all the questions and options so you decide to go with the template which is prebuilt for a particular topic.

**Comment by Trishank-K** [comment]
Okay Got it 👍

**Comment by Trishank-K** [comment]
Hey @shubhansu-kr I've tested all the backend routes and I only found issue in auth routes for which I have created a pr at #53

**Comment by shubhansu-kr** [comment]
@Trishank-K Assigned
