### ISSUE TITLE
[Server] Implement achivements and badges API routes.

### ISSUE THREAD

**Issue by shubhansu-kr** [mvp-2003/Quikz#28]
## Gamification Features (Badges, Achievements)
**Description:**  
Implement a gamification system where users can earn badges and achievements based on their quiz performance and participation.

**Tasks:**
- Create badge/achievement model.
- Implement routes to fetch and update user achievements.
- Implement logic to award badges for specific actions (e.g., quiz completion, high scores).

**Dependencies:**  
- **Quiz Management** (Issue 2) and **Polls & Voting** (Issue 3) for tracking user actions.
- **Leaderboard** (Issue 4) for tracking high scores.

**Guidelines for Assignee:**
- Comment on the issue with the model and rules for awarding badges/achievements.

**Comment by Trishank-K** [comment]
Hey! I would Love to work on this issue

I am thinking of implementing these models : 

`// Badge Schema`
`const badgeSchema = new mongoose.Schema({`
  `name: {`
`    type: String,`
`    required: true,`
`  },`
`  description: {`
`    type: String,`
`  },`
`  criteria: {`
`    type: String, // Description of the conditions to earn the badge`
`    required: true,`
`  },`
`  icon: {`
`    type: String, // URL or path to badge icon`
`  },`
`  createdAt: {`
`    type: Date,`
`    default: Date.now,`
`  },`
`});`


`// Achievement Schema`
`const achievementSchema = new mongoose.Schema({`
`  userId: {`
`    type: mongoose.Schema.Types.ObjectId,`
`    ref: 'User',`
`    required: true,`
`  },`
`  badgeId: {`
`    type: mongoose.Schema.Types.ObjectId,`
`    ref: 'Badge',`
`    required: true,`
`  },`
`  achievedAt: {`
`    type: Date,`
`    default: Date.now,`
`  },`
`});`


and for the rules for awarding:

- Completion-based: "Complete 5 quizzes to earn the 'Quiz Enthusiast' badge."
- Performance-based: "Score 90% or higher in a quiz to earn the 'Top Scorer' badge."
- Participation-based: "Participate in 3 polls to earn the 'Active Voter' badge."

also maybe level system such as:

- Bronze Quiz Master: Complete 5 quizzes.
- Silver Quiz Master: Complete 15 quizzes.
- Gold Quiz Master: Complete 30 quizzes.


If you have any more suggestions, please do tell!

**Comment by shubhansu-kr** [comment]
You would have to wait for quiz issue to be implemented right ? Or are you planning to do both

**Comment by Trishank-K** [comment]
Well I can do both! 
Can you link the other issue here? I can't seem to find the quiz issue

**Comment by shubhansu-kr** [comment]
#21 , 

@Trishank-K Schema design looks good to me. How do you plan to trigger those assignment. Will they be instant on the completion of the criteria or will they be scheduled with a cron job which will verify achievement for each user in a fixed interval ? 

Please make sure to make this scalable, as the achievements will be added depending on the event. Better to make a route which will enable admins to create badge/achievement. 

Next Step : Come up with the routes plan.

**Comment by Trishank-K** [comment]
Hey @shubhansu-kr  

I was thinking of using an Event-Driven Architecture to handle real-time tasks like badge distribution when quizzes end :

- Emit an Event When a Quiz Ends: When a quiz is completed, the backend triggers an event, such as quizCompleted.
- Event Listener/Consumer: You can have a listener or a message queue RabbitMQ(preferrably) subscribed to these events. As soon as a quizCompleted event is received, it fetches the results, determines the top three winners, and assigns badges to them in the database.
- Notification/Reward: The listener then either sends notifications or processes badge assignments, ensuring immediate response without the use of a cron job.


and the API routes for badges and achievments can be as follows:

- GET /badges: Fetch all available badges.
- GET /badge/:badgeId: Fetch details of a specific badge.
- GET /user/:userId/achievements: Fetch all achievements for a specific user.
- POST /user/:userId/achievements: Award a new badge to a user.
- GET /badge/:badgeId/achievements: Fetch all users who have earned a specific badge.
- DELETE /user/:userId/achievement/:achievementId: Delete a user’s achievement (admin-only).
- POST /badges: Create a new badge (admin-only).
- POST /achievments: Create a new achievment (admin-only).

Should I start working on both or just the badges/achievments for now?

**Comment by shubhansu-kr** [comment]
Sounds right ! Start with the Badge/achievement only.

**Comment by Trishank-K** [comment]
Starting the work don't forget to add me as a assignee to this issue
Thank You!

**Comment by shubhansu-kr** [comment]
You already are the assignee

**Comment by Trishank-K** [comment]
Apologies for the overlook 😅
