### ISSUE TITLE
[Server] Implement Feedback API routes 

### ISSUE THREAD

**Issue by shubhansu-kr** [mvp-2003/Quikz#29]
## Feedback & Reviews
**Description:**  
Allow users to provide feedback and rate quizzes after completion.

**Tasks:**
- Create feedback model.
- Implement routes for submitting and retrieving feedback.
- Integrate feedback with quiz results to allow users to leave reviews after completion.

**Dependencies:**  
- **Quiz Management** (Issue 2) since users will be reviewing quizzes.

**Guidelines for Assignee:**
- Comment on the issue with the feedback model and the routes for submitting/viewing feedback.

**Comment by Avinashs7** [comment]
Can you assign it to me.

**Comment by shubhansu-kr** [comment]
@Avinashs7 You can start working now
