### ISSUE TITLE
[Server] Implement Tags & Categories API routes

### ISSUE THREAD

**Issue by shubhansu-kr** [mvp-2003/Quikz#30]
## Tags & Categories
**Description:**  
Implement tags and categories to organize quizzes, polls, and questions for better user filtering and search capabilities.

**Tasks:**
- Create tags/categories model.
- Implement routes to create and manage tags/categories.
- Integrate tagging into quiz and question creation to allow for easier filtering.

**Dependencies:**  
- **Quiz Management** (Issue 2) and **Question Bank** (Issue 5) for tagging quizzes and questions.

**Guidelines for Assignee:**
- Comment on the issue with the model and routes for tagging.
- Follow RESTful conventions for filtering routes.

**Comment by Horsmanayo** [comment]
Hi @shubhansu-kr, I would love to work on this, I however noticed the user docker, I dont have docker setup on my PC, would there be a guide to do the setup?

**Comment by shubhansu-kr** [comment]
Hi @Horsmanayo, Thank you for showing interest. You don't need to worry about docker, we will configure it. If the express application runs fine and all the functionality works , you are good to go.

**Comment by shubhansu-kr** [comment]
You can start contributing. All the best

**Comment by Horsmanayo** [comment]
Hi @shubhansu-kr, I created a PR for this issue. Kindly check it out and give feedbacks as this is my first time contributing to  open source.

**Comment by shubhansu-kr** [comment]
Hi @Horsmanayo ,  

I understand this is your first contribution so lets try to follow the guidelines. As mentioned in the description please share your suggested changes and schema design here in the convo. Get the approach approved and then start implementation.

For now you can do this and update the PR as per the changes/suggestion you get from the reviewer. 

Thank you

**Comment by Horsmanayo** [comment]
Thank you for your feedback @shubhansu-kr, I understand the need to align with the contribution process and will follow the approach outlined.

Schema design 

`const tagSchema = new mongoose.Schema({
  name: { type: String, required: true, unique: true },
  description: String,
});`

Suggested changes includes 
- Creating a schema for tags creation, since tags has the one-to-many relationship, they are to be attached to quiz question
- Create a controller for performing crud operation on tags 
- Create route handlers 
- Create a reusable pagination function in the utils folder so all pagination are handled same way across board

**Comment by shubhansu-kr** [comment]
How will we establish quiz to tag relation? Do we need to update the quiz schema as well ? 
What feature will you be implementing with tags ? 
Who will be eligible to create tags ? Can it be created by anyone and be used by anyone ? 
Should we not have an id in the tag schema ? 

There are a lot of things to cover. Be more verbose about it. 
 List all the use cases. 
 List all the routes required to achieve the use cases. 
List the approach for implementation.

**Comment by Horsmanayo** [comment]
Tag-Quiz relationship 
`const quizSchema = new mongoose.Schema({
  title: { type: String, required: true },
  description: String,
  tags: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Tag' }],  //referencing tag relationship 
});`

Other fields needed by quiz can be added 

**Tag Creation and Association:**

- Authorized users (i.e., users with the permission to create quizzes) will also be able to create tags when creating or updating a quiz.
- Users can search for existing tags when creating a quiz or add new ones if necessary.
- Example use case: A user creating a quiz on JavaScript will be able to add tags like JavaScript, Frontend, or create new tags that describe the quiz.

**Tag Filtering for Quiz Takers:**
- Quiz takers can filter quizzes based on tags. For example, if a quiz has the tag JavaScript, users should be able to search for all quizzes tagged with JavaScript.

**Tag Suggestion by Quiz Takers:**
- I propose allowing users to suggest or add tags after attempting a quiz. This enhances user engagement and adds relevant tags from their perspective.

 **Eligibility for Creating Tags**
- Only authorized users (users who can create quizzes) will be able to create new tags, as tags directly relate to quizzes.
However, quiz takers will be able to suggest or add tags after attempting a quiz (subject to review or auto-approval based on preferences).

**MongoDB IDs for Tags**
- The MongoDB-generated ID (_id) will be sufficient for identifying tags, so we don’t need an additional custom ID field.

**Use Cases**
- Create and attach tags to a quiz: Authorized users can create tags while creating or updating a quiz.
- Search quizzes by tag: Quiz takers can search for quizzes by filtering with tags.
- Add suggested tags: Quiz takers can suggest or add tags after attempting a quiz.
- Manage tags: Admin users can edit, delete, or manage tags if needed.

**Required Routes**
Here’s a list of routes needed for the tag-related functionality:

- POST /tags: Create a new tag (authorized users only).
- GET /tags: Get all available tags with optional pagination and search.
- GET /tags/: Get a single tag by its ID.
- PUT /tags/: Update an existing tag (admin or authorized users).
- DELETE /tags/: Delete a tag (admin only).
- POST /quizzes: Attach a tag to a quiz while creating or updating a quiz.
- GET /quizzes?tags=tagName: Filter quizzes by tag name.

**Comment by shubhansu-kr** [comment]
Yes, That issue is resolved. You can work on tags related endpoint.

**Comment by Horsmanayo** [comment]
Hi @shubhansu-kr , somethings to note 

- There is no endpoint for get all quiz, I have to create that to test filter by tags

Can i go ahead with this?
