### ISSUE TITLE
[FEATURE]  Can we work on this design?

### ISSUE THREAD

**Issue by DanielAgbeni** [mvp-2003/Quikz#40]
## Feature Request

Can we work on this design
(https://www.figma.com/design/TV1xAvWKlqKYRctr5Mz4RZ/Quiz-App-Design-(Community)?node-id=0-1&node-type=canvas&t=54tRcCNIhkrMjnSf-0)

**Comment by shubhansu-kr** [comment]
@DanielAgbeni , This looks fire. We are building a web app so would have to ask you to design for desktop resolutions as well. Mobile version looks good.

There is an ongoing SIM for design #12 

You can post it there for visibility

**Comment by shubhansu-kr** [comment]
Closing Issue. Follow #12
