### ISSUE TITLE
[FEATURE] Create the quiz creation page.

### ISSUE THREAD

**Issue by asmb123** [mvp-2003/Quikz#50]
### **Additional Context**
*  Look into the UI design inspo at https://www.figma.com/design/s0eI8YDamF3Gqh3Bt5et99/asmbDev?node-id=116-4&t=IzEZnyEPebG9bJvh-1
* Make it like in the design or better
* Make it responsive
* Use framer motion for animating the page's load/unload to make the UI more user friendly.
* Color code of dark mode and light mode for button, bg, text has been set up in the <code>tailwind.config.js</code> file, changing it will create inconsistency in the UI.
* example of using the color code : <code>className="bg-radial-light dark:bg-radial-dark"</code> this className changes according to the theme.
* this page should be visible when the user visits the <code>/create</code> route.
* Once created add the details in <code>documentation.md</code>, look for it in <code>server/documentation.md</code>

**Comment by Alienimnida** [comment]
Hello can I take this up?
