### ISSUE TITLE
[FEATURE] Light/Dark mode across the app.

### ISSUE THREAD

**Issue by asmb123** [mvp-2003/Quikz#51]

**Comment by coder483** [comment]
ya i can work on this

**Comment by shubhansu-kr** [comment]
@coder483 All the best

**Comment by Aditya-PS-05** [comment]
Can you assign me this issue?

**Comment by shubhansu-kr** [comment]
@Aditya-PS-05 I assigned this task to @coder483 previously. I will wait for two days for him to respond with updates. If he is not working on this task, will assign you this issue. Thanks
