### ISSUE TITLE
Getting 404 error while clicking on create a quiz or join a quiz

### ISSUE THREAD

**Issue by Alienimnida** [mvp-2003/Quikz#52]
The frontend is not connected with the backend routes

**Comment by asmb123** [comment]
@Alienimnida that is because there is no frontend route other than '/' is created yet.
Request to get assigned in issue #50 .

**Comment by shubhansu-kr** [comment]
@Alienimnida You can integrate post resolution of issue #50. Assigning you this.

**Comment by shubhansu-kr** [comment]
Thanks @asmb123 for helping

**Comment by Alienimnida** [comment]
Okok will get it done

**Comment by Avinashs7** [comment]
Can you assign this to me!

**Comment by shubhansu-kr** [comment]
Frontend was not integrated to call any api, so basically on button click nothing was happening. Since we did not have mocks for create quiz app page, we didn't integrate.

**Comment by shubhansu-kr** [comment]
You can check the code base and let me know your approach and requirement to fix this.

**Comment by Avinashs7** [comment]
I have gone through the code base, I can create routes and handle the API request to store them.

Requirement:
I want someone to write the quiz question input and design it as mentioned in #50.

Can I write the components and leave the section to design accordingly and write the context API for storage?

**Comment by shubhansu-kr** [comment]
Sure

**Comment by shubhansu-kr** [comment]
Resolving
