### ISSUE TITLE
[BUG] On login or register the JWT token is being created but not being set in headers!

### ISSUE THREAD

**Issue by Trishank-K** [mvp-2003/Quikz#53]
### **Description**
Whenever the user logs in or signs up the token is only generated but there is no implementation to set it in header so that middleware can actually verify the token 

### **Steps to Reproduce**

1. Login or sign up
2. Check the headers in postman
3. There is no authorization header

### **Expected Behavior**
In an ideal case scenario the backend should send a response for cookies eg. 
`res.cookie('Authorization', token)`

### **Actual Behavior**
Currently, there are no headers or cookies being set as such

### **Screenshots**
- Here just the token is created and being sent to Frontend but nor being set as header or cookie
- 
![image](https://github.com/user-attachments/assets/4f9b8661-cbdd-4701-aeaa-365a9648184f)

### **System Info**

- **OS**: [Windows]
- **Browser**: [Brave]

**Comment by shubhansu-kr** [comment]
@Trishank-K You resolved this, right ?

**Comment by Trishank-K** [comment]
Just got out of my head!
Will fix this asap
